<template>
<div class='row'>
 <div>
      <h3 class='in-site-head'>Terms &amp; Conditions</h3>
  <q-card class='game-tile-card'>
  <q-card-title>
    Terms &amp; Conditions
  </q-card-title>
  <q-card-separator />
  <q-card-main>
    <p class='static-card-title'>Ultimate Cricket Fantasy (UCF)</p>
    <p class='static-card-content'>"UCF is not associated or affiliated in any way with Apple, private or government cricket or football leagues/tournaments unless otherwise stated. We are also not associated with and claim no official status with any official or non-official sportsman or team. We do not promote, support or encourage betting or gambling in any form"</p>
    <q-card-separator/>
    <br/>
    <p class='static-card-title'>1.Intellectual Property Rights</p>
    <p class='static-card-content'>UCF includes a combination of content created by UCF, its partners, licensors, associates and/or Users. The intellectual property rights (“Intellectual Property Rights”) in all software underlying UCF.com and Fantasy gaming and material published on UCF.com, including (but not limited to) games, leagues, software, advertisements, written content, photographs, graphics, images, illustrations, marks, logos, audio or video clippings and Flash animation, is owned by UCF, its partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or content on UCF.com either in whole or in part without an express written license from UCF.</p>
    <p class='static-card-content'>Users may request permission to use any UCF.com content by writing in to info@UCF.com</p>
    <p class='static-card-content'>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available on UCF.com (“Users’ Content”). Each User represents and warrants that he/she owns all Intellectual Property Rights in the User’s Content and that no part of the User’s Content infringes any third party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights of any third party on UCF.com. Users agree to identify and hold harmless UCF, its directors, employees, affiliates and assigns against all costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on UCF.com, by such User or through the User’s commissions or omissions.</p>
     <p class='static-card-content'>Users hereby grant to UCF and its affiliates, partners, licensors and associates a worldwide, irrevocable, royalty-free, non-exclusive, sub-licensable license to use, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users’ Content for any of the following purposes:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Displaying Users’ Content on UCF.com</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Distributing Users’ Content, either electronically or via other media, to other Users seeking to download or otherwise acquire it, and/or</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Storing Users’ Content in a remote database accessible by end users, for a charge.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> This license shall apply to the distribution and the storage of Users’ Content in any form, medium, or technology..</p>
     <p class='static-card-content'>All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on UCF.com(s) belonging to any person (including User), entity or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to UCF.</p>
    <p class='static-card-title'>2.Usage of UltimateCricketFantasy.com</p>
    <p class='static-card-content'>Any person utilizing UCF.com or the UCF App (“User”) or accessing the Fantasy Gaming therein including participation in the various leagues and, games (including fantasy games), being conducted on UCF.com (“league(s)”) shall be bound by these Terms and Conditions, and all other rules, regulations, and terms of use referred to herein or provided by UCF in relation to any Fantasy gaming.</p>
    <p class='static-card-content'>UCF shall be entitled to modify these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF in relation to any gaming feature, at any time, by posting the same on UCF.com. Use of UCF constitutes the User’s acceptance of such Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF in relation to any Fantasy gaming, as may be amended from time to time. UCF may also notify the User of any change or modification in these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF, by way of sending an email to the User’s registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF.</p>
    <p class='static-card-content'>Certain fantasy Features being provided on UCF may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.</p>
    <p class='static-card-content'>UCF may, at its sole and absolute discretion:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Restrict, suspend, or terminate any User’s access to all or any part of UCF.com or UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Change, suspend, or discontinue all or any part of the facilities provided.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Deactivate or delete a User’s account and all related information and files on the account.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Reject, move, or remove any material that may be submitted by a User.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Move or remove any content that is available on UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Establish general practices and limits concerning use of UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Revise or make additions to the roster of players available for selection in a league on account of revisions to the roster of players involved in the relevant Sports Event.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Assign its rights and liabilities to all User accounts hereunder to any entity (post intimation of such assignment shall be sent to all Users to their registered email ids).</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Any breach or inadequate performance by the User of any of these Terms and Conditions.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Any circumstances beyond the reasonable control of UCF.</p>
     <p class='static-card-content'>  Users consent to receiving communications such as announcements, administrative messages and advertisements from UCF or any of its partners, licensors or associates.</p>
      <p class='static-card-title'>3.Third Party Sites, Services and Products</p>
    <p class='static-card-content'>UCF.com may contain links to other Internet sites owned and operated by third parties. Users’ use of each of those sites is subject to the conditions, if any, posted by the sites. UCF does not exercise control over any Internet sites apart from UCF.com, and cannot be held responsible for any content residing in any third party Internet site. UCF’s inclusion of third-party content or links to third-party Internet sites is not an endorsement by UCF of such third-party Internet site.</p>
    <p class='static-card-content'>Users’ correspondence, transactions or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. Users' correspondence, transactions and usage of the services of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services of such third party. User agrees that UCF will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions with third parties. Any questions, complaints, or claims related to any third party product or service should be directed to the appropriate vendor.</p>
    <p class='static-card-content'>UCF.com contains content that is created by UCF as well as content provided by third parties. UCF does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not relied upon by the Users in utilizing the Fantasy gaming provided on UCF.com including while participating in any of the leagues hosted on UCF.com.</p>
     <p class='static-card-title'>4.Privacy Policy</p>
    <p class='static-card-content'>All information collected from Users, such as registration and payment information, is subject to UCF’s Privacy Policy which is available at Privacy Policy.</p>
     <p class='static-card-title'>5.User Guidelines</p>
    <p class='static-card-content'>Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use of the Website. In the event User does not abide by these Terms and Conditions and all other rules, regulations and terms of use, UCF may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Restricting, suspending, or terminating any User’s access to all or any part of UCF.com'fantasy gaming.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Deactivating or deleting a User’s account and all related information and files on the account. Any amount remaining unused in the User’s Game account or Winnings Account on the date of deactivation or deletion shall be transferred to the User’s bank account on record with UCF subject to a processing fee (if any) applicable on such transfers as set out herein.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>   Refraining from awarding any prize(s) to such User.</p>
     <p class='static-card-content'>Users agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by UCF). Users further agree to update and keep updated their registration information.</p>
     <p class='static-card-content'>A User shall not register or operate more than one User account with UCF.</p>
     <p class='static-card-content'>Users agree to ensure that they can receive all communication from UCF by marking e-mails from UCF.com as part of their “safe senders” list. UCF shall not be held liable if any e-mail remains unread by a User as a result of such e-mail getting delivered to the User’s junk or spam folder.</p>
     <p class='static-card-content'>Any password issued by UCF to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify UCF of any unauthorized use of their passwords or accounts or any other breach of security.</p>
     <p class='static-card-content'>Users agree to exit/log-out of their accounts at the end of each session. UCF shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.</p>
     <p class='static-card-content'>Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorized third-party software designed to modify or interfere with UCF.comFantasy gaming and/or UCF experience or assist in such activity.</p>
     <p class='static-card-content'>Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying UCF.com or Fantasy gaming.</p>
     <p class='static-card-content'>Users agree that without UCF’s express written consent, they shall not modify or cause to be modified any files or software that are part of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support UCF.com or the Fantasy gaming (each a “Server”); or (2) the enjoyment of UCF.com's Fantasy gaming by any other User or person.</p>
     <p class='static-card-content'>Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt UCF.com's Fantasy gaming or any other person’s use or enjoyment of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to UCF.com's Fantasy gaming by any means other than the User interface provided by UCF, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Without limiting the foregoing, Users agree not to use UCF.com for any of the following:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To harass, stalk, threaten, or otherwise violate any legal rights of other individuals.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To publish, post, upload, e-mail, distribute, or disseminate (collectively, “Transmit”) any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, UCF.com, any software, hardware, or telecommunications equipment.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To advertise, offer or sell any goods or services for any commercial purpose on UCF.com without the express written consent of UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit content regarding services, products, surveys, leagues, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To advertise, offer or sell any goods or services for any commercial purpose on UCF.com without the express written consent of UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit content regarding services, products, surveys, leagues, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To download any file, decompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To restrict or inhibit any other user from using and enjoying any public area within our sites.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To collect or store personal information about other Users.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To interfere with or disrupt UCF.com, servers, or networks.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To impersonate any person or entity, including, but not limited to, a representative of UCF, or falsely state or otherwise misrepresent User’s affiliation with a person or entity.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through UCF.com or to manipulate User’s presence on UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To take any action that imposes an unreasonable or disproportionately large load on our infrastructure.</p>
     <p class='static-card-content'> Unauthorized access to UCF.com is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access UCF.com by any means other than through the interface that is provided by UCF for use in accessing UCF.com. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.</p>
     <p class='static-card-content'> Use of UCF.com is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit UCF’s right to comply with governmental, court, and law-enforcement requests or requirements relating to Users’ use of UCF.com.</p>
     <p class='static-card-content'> Users may contact info@UCF.com with problems or questions, as appropriate.</p>
     <p class='static-card-content'> Persons below the age of eighteen (18) years are required to seek permission or consent from their parents or legal guardians before furnishing data, participating or entering on UCF.com or the Fantasy gaming or inter alia, in the league, uploading pictures, playing games or being part, directly or indirectly, of any activity on UCF.com. Entry to UCF.com without consent from parent/s or legal guardian and consequent participation in any activity on UCF Website is not permitted and such person is subject to disqualification at the sole and absolute discretion of UCF, whenever it comes to the knowledge of UCF.</p>
     <p class='static-card-content'> UCF believes that parents should supervise their children's online activities and consider using parental control tools available from online services and software manufacturers that help provide a child-friendly online environment. These tools can also prevent children from disclosing online their name, address and other personal information without parental permission.</p>
     <p class='static-card-content'> Although persons below the age of 18 years are allowed to use certain Fantasy gaming Features on the UCF.com with the consent of their parent/s or legal guardians, they may not (where expressly stated in the rules of the league) participate in league(s) hosted by UCF.</p>
     <p class='static-card-content'> UCF may not be held responsible for any content contributed by Users on the UCF.com.</p>
      <p class='static-card-title'>6.Registration process</p>
    <p class='static-card-content'>In order to register for the league(s), Participants are required to accurately provide the following information:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Full Name:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Team Name(s):</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>E-mail address:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Password:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>State of Residence:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Gender:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Date of Birth:</p>
    <p class='static-card-content'>Participants are also required to confirm that they have read, and shall abide by, these Terms and Conditions.</p>
    <p class='static-card-content'>In the event a Participant indicates, while entering an address, that he/she is a resident of Assam, Odisha and Telangana, such Participant will not be permitted to proceed to sign up for any round in the paid version of the league as described below.

</p>
    <p class='static-card-content'>Once the Participants have entered the above information, and clicked on the “register” tab, and such Participants are above the age of 18 years, they are sent an email confirming their registration and containing their login information.</p>

     </q-card-main>
</q-card>
 </div>
</div>
</template>
<script>
export default {
  
}
</script>
