<template>
<div class='row'>
 <div>
      <h3 class='in-site-head'>Terms &amp; Conditions</h3>
  <q-card class='game-tile-card'>
  <q-card-title>
    Terms &amp; Conditions
  </q-card-title>
  <q-card-separator />
  <q-card-main>
    <p class='static-card-title'>Ultimate Cricket Fantasy (UCF)</p>
    <p class='static-card-content'>"UCF is not associated or affiliated in any way with Apple, private or government cricket or football leagues/tournaments unless otherwise stated. We are also not associated with and claim no official status with any official or non-official sportsman or team. We do not promote, support or encourage betting or gambling in any form"</p>
    <q-card-separator/>
    <br/>
    <p class='static-card-title'>1.Intellectual Property Rights</p>
    <p class='static-card-content'>UCF includes a combination of content created by UCF, its partners, licensors, associates and/or Users. The intellectual property rights (“Intellectual Property Rights”) in all software underlying UCF.com and Fantasy gaming and material published on UCF.com, including (but not limited to) games, leagues, software, advertisements, written content, photographs, graphics, images, illustrations, marks, logos, audio or video clippings and Flash animation, is owned by UCF, its partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or content on UCF.com either in whole or in part without an express written license from UCF.</p>
    <p class='static-card-content'>Users may request permission to use any UCF.com content by writing in to info@UCF.com</p>
    <p class='static-card-content'>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available on UCF.com (“Users’ Content”). Each User represents and warrants that he/she owns all Intellectual Property Rights in the User’s Content and that no part of the User’s Content infringes any third party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights of any third party on UCF.com. Users agree to identify and hold harmless UCF, its directors, employees, affiliates and assigns against all costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on UCF.com, by such User or through the User’s commissions or omissions.</p>
     <p class='static-card-content'>Users hereby grant to UCF and its affiliates, partners, licensors and associates a worldwide, irrevocable, royalty-free, non-exclusive, sub-licensable license to use, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users’ Content for any of the following purposes:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Displaying Users’ Content on UCF.com</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Distributing Users’ Content, either electronically or via other media, to other Users seeking to download or otherwise acquire it, and/or</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Storing Users’ Content in a remote database accessible by end users, for a charge.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> This license shall apply to the distribution and the storage of Users’ Content in any form, medium, or technology..</p>
     <p class='static-card-content'>All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on UCF.com(s) belonging to any person (including User), entity or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to UCF.</p>
    <p class='static-card-title'>2.Usage of UltimateCricketFantasy.com</p>
    <p class='static-card-content'>Any person utilizing UCF.com or the UCF App (“User”) or accessing the Fantasy Gaming therein including participation in the various leagues and, games (including fantasy games), being conducted on UCF.com (“league(s)”) shall be bound by these Terms and Conditions, and all other rules, regulations, and terms of use referred to herein or provided by UCF in relation to any Fantasy gaming.</p>
    <p class='static-card-content'>UCF shall be entitled to modify these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF in relation to any gaming feature, at any time, by posting the same on UCF.com. Use of UCF constitutes the User’s acceptance of such Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF in relation to any Fantasy gaming, as may be amended from time to time. UCF may also notify the User of any change or modification in these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF, by way of sending an email to the User’s registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by UCF.</p>
    <p class='static-card-content'>Certain fantasy Features being provided on UCF may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.</p>
    <p class='static-card-content'>UCF may, at its sole and absolute discretion:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> Restrict, suspend, or terminate any User’s access to all or any part of UCF.com or UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Change, suspend, or discontinue all or any part of the facilities provided.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Deactivate or delete a User’s account and all related information and files on the account.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Reject, move, or remove any material that may be submitted by a User.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Move or remove any content that is available on UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Establish general practices and limits concerning use of UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Revise or make additions to the roster of players available for selection in a league on account of revisions to the roster of players involved in the relevant Sports Event.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Assign its rights and liabilities to all User accounts hereunder to any entity (post intimation of such assignment shall be sent to all Users to their registered email ids).</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Any breach or inadequate performance by the User of any of these Terms and Conditions.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Any circumstances beyond the reasonable control of UCF.</p>
     <p class='static-card-content'>  Users consent to receiving communications such as announcements, administrative messages and advertisements from UCF or any of its partners, licensors or associates.</p>
      <p class='static-card-title'>3.Third Party Sites, Services and Products</p>
    <p class='static-card-content'>UCF.com may contain links to other Internet sites owned and operated by third parties. Users’ use of each of those sites is subject to the conditions, if any, posted by the sites. UCF does not exercise control over any Internet sites apart from UCF.com, and cannot be held responsible for any content residing in any third party Internet site. UCF’s inclusion of third-party content or links to third-party Internet sites is not an endorsement by UCF of such third-party Internet site.</p>
    <p class='static-card-content'>Users’ correspondence, transactions or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. Users' correspondence, transactions and usage of the services of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services of such third party. User agrees that UCF will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions with third parties. Any questions, complaints, or claims related to any third party product or service should be directed to the appropriate vendor.</p>
    <p class='static-card-content'>UCF.com contains content that is created by UCF as well as content provided by third parties. UCF does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not relied upon by the Users in utilizing the Fantasy gaming provided on UCF.com including while participating in any of the leagues hosted on UCF.com.</p>
     <p class='static-card-title'>4.Privacy Policy</p>
    <p class='static-card-content'>All information collected from Users, such as registration and payment information, is subject to UCF’s Privacy Policy which is available at Privacy Policy.</p>
     <p class='static-card-title'>5.User Guidelines</p>
    <p class='static-card-content'>Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use of the Website. In the event User does not abide by these Terms and Conditions and all other rules, regulations and terms of use, UCF may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Restricting, suspending, or terminating any User’s access to all or any part of UCF.com'fantasy gaming.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>  Deactivating or deleting a User’s account and all related information and files on the account. Any amount remaining unused in the User’s Game account or Winnings Account on the date of deactivation or deletion shall be transferred to the User’s bank account on record with UCF subject to a processing fee (if any) applicable on such transfers as set out herein.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon>   Refraining from awarding any prize(s) to such User.</p>
     <p class='static-card-content'>Users agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by UCF). Users further agree to update and keep updated their registration information.</p>
     <p class='static-card-content'>A User shall not register or operate more than one User account with UCF.</p>
     <p class='static-card-content'>Users agree to ensure that they can receive all communication from UCF by marking e-mails from UCF.com as part of their “safe senders” list. UCF shall not be held liable if any e-mail remains unread by a User as a result of such e-mail getting delivered to the User’s junk or spam folder.</p>
     <p class='static-card-content'>Any password issued by UCF to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify UCF of any unauthorized use of their passwords or accounts or any other breach of security.</p>
     <p class='static-card-content'>Users agree to exit/log-out of their accounts at the end of each session. UCF shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.</p>
     <p class='static-card-content'>Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorized third-party software designed to modify or interfere with UCF.comFantasy gaming and/or UCF experience or assist in such activity.</p>
     <p class='static-card-content'>Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying UCF.com or Fantasy gaming.</p>
     <p class='static-card-content'>Users agree that without UCF’s express written consent, they shall not modify or cause to be modified any files or software that are part of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support UCF.com or the Fantasy gaming (each a “Server”); or (2) the enjoyment of UCF.com's Fantasy gaming by any other User or person.</p>
     <p class='static-card-content'>Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt UCF.com's Fantasy gaming or any other person’s use or enjoyment of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to UCF.com's Fantasy gaming by any means other than the User interface provided by UCF, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of UCF.com's Fantasy gaming.</p>
     <p class='static-card-content'>Without limiting the foregoing, Users agree not to use UCF.com for any of the following:</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To harass, stalk, threaten, or otherwise violate any legal rights of other individuals.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To publish, post, upload, e-mail, distribute, or disseminate (collectively, “Transmit”) any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, UCF.com, any software, hardware, or telecommunications equipment.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To advertise, offer or sell any goods or services for any commercial purpose on UCF.com without the express written consent of UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit content regarding services, products, surveys, leagues, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To advertise, offer or sell any goods or services for any commercial purpose on UCF.com without the express written consent of UCF.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To Transmit content regarding services, products, surveys, leagues, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To download any file, decompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To restrict or inhibit any other user from using and enjoying any public area within our sites.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To collect or store personal information about other Users.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To interfere with or disrupt UCF.com, servers, or networks.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To impersonate any person or entity, including, but not limited to, a representative of UCF, or falsely state or otherwise misrepresent User’s affiliation with a person or entity.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through UCF.com or to manipulate User’s presence on UCF.com.</p>
     <p class='static-card-content'><q-icon name='trending flat'></q-icon> To take any action that imposes an unreasonable or disproportionately large load on our infrastructure.</p>
     <p class='static-card-content'> Unauthorized access to UCF.com is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access UCF.com by any means other than through the interface that is provided by UCF for use in accessing UCF.com. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.</p>
     <p class='static-card-content'> Use of UCF.com is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit UCF’s right to comply with governmental, court, and law-enforcement requests or requirements relating to Users’ use of UCF.com.</p>
     <p class='static-card-content'> Users may contact info@UCF.com with problems or questions, as appropriate.</p>
     <p class='static-card-content'> Persons below the age of eighteen (18) years are required to seek permission or consent from their parents or legal guardians before furnishing data, participating or entering on UCF.com or the Fantasy gaming or inter alia, in the league, uploading pictures, playing games or being part, directly or indirectly, of any activity on UCF.com. Entry to UCF.com without consent from parent/s or legal guardian and consequent participation in any activity on UCF Website is not permitted and such person is subject to disqualification at the sole and absolute discretion of UCF, whenever it comes to the knowledge of UCF.</p>
     <p class='static-card-content'> UCF believes that parents should supervise their children's online activities and consider using parental control tools available from online services and software manufacturers that help provide a child-friendly online environment. These tools can also prevent children from disclosing online their name, address and other personal information without parental permission.</p>
     <p class='static-card-content'> Although persons below the age of 18 years are allowed to use certain Fantasy gaming Features on the UCF.com with the consent of their parent/s or legal guardians, they may not (where expressly stated in the rules of the league) participate in league(s) hosted by UCF.</p>
     <p class='static-card-content'> UCF may not be held responsible for any content contributed by Users on the UCF.com.</p>
      <p class='static-card-title'>6.Registration process</p>
    <p class='static-card-content'>In order to register for the league(s), Participants are required to accurately provide the following information:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Full Name:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Team Name(s):</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>E-mail address:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Password:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>State of Residence:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Gender:</p>
    <p class='static-card-content'><q-icon name='trending flat'></q-icon>Date of Birth:</p>
    <p class='static-card-content'>Participants are also required to confirm that they have read, and shall abide by, these Terms and Conditions.</p>
    <p class='static-card-content'>In the event a Participant indicates, while entering an address, that he/she is a resident of Assam, Odisha and Telangana, such Participant will not be permitted to proceed to sign up for any round in the paid version of the league as described below.

</p>
    <p class='static-card-content'>Once the Participants have entered the above information, and clicked on the “register” tab, and such Participants are above the age of 18 years, they are sent an email confirming their registration and containing their login information.</p>
    <p class='static-card-title'>7.League, Participation and Prizes</p>
    <p class='static-card-content'>As part of its Fantasy gaming Features UCF may also conduct league(s) on the UCF.com, Currently, UCF provides the following : 1) A fantasy cricket game Individual users wishing to participate in the Fantasy gaming ("Participant(s)") are invited to create their own fantasy teams ("Team(s)") consisting of real-life cricketers involved in the real-life cricket match (as applicable), series or tournament (each a “Sport Event”) to which the fantasy game relates. UCF offers Participants fantasy game league(s) relating to Sport Event, and Participants can participate in such league(s) with their Teams. Teams are awarded points on the basis of the real-life cricketers’ (as applicable) performances at the end of a designated match, round or tournament of the league(s). The Participant(s) whose Team(s) have achieved the highest aggregate score(s) in the league(s) shall be declared winners ("Winners"). In certain pre-specified leagues, UCF may declare more than one Winner and distribute prizes to such Winners in increasing order of their Team's aggregate score at the end of the designated round(s) of the leagues.The league(s) across both Fantasy gaming shall, in addition to the Terms and Conditions, rules and regulations mentioned herein, be governed by:</p>
      <p class='static-card-content'><q-icon name='trending flat'></q-icon> "Fantasy Rules" available at How To Play – Fantasy Cricket Other rules and regulations (including rules and regulation in relation to any payments made to participate in the league(s); and all Participants agree to abide by the same.</p>
      <p class='static-card-content'>Currently, there are paid versions of the league(s) made available by UCF.com Users may participate in the league(s) by paying the pre-defined amount as provided on the relevant league page. The Participant with the highest aggregate points at the end of the pre-determined round shall be eligible to win a pre-designated prize, as stated on the relevant league(s) page.</p>
      <p class='static-card-content'>A Participant may create different Teams for participation in league(s) offered in relation to a Sport Event across the Fantasy gaming. However, unless UCF specifies otherwise in relation to any league ("Multiple Entry league"), Participants acknowledge and agree that they may enter only one Team in any league offered in relation to a Sport Event. In the case of a Multiple Entry league, a Participant may enter more than one Team in a single Multiple Entry league, however on submitting more than one Team for participation in a single Multiple Entry league, the Participant will not be permitted to edit or revise the Teams so submitted for participation in such Multiple Entry league. In addition, it is expressly clarified that UCF may, from time to time, restrict the maximum number of Teams that may be created by a single User account (for each format of the Fantasy gaming) or which a single User account may enter in a particular Multiple Entry league, in each case to such number as determined by UCF in its sole discretion.</p>
      <p class='static-card-content'>UCF shall collect a pre-designated fee for access to the Fantasy gaming from each Participant in relation to the league(s). In the event a Participant indicates, while entering an address, that he/she is a resident of Assam, Odisha and Telangana, such Participant will not be permitted to proceed to sign up for the round or league and may not participate in any paid version of the league(s).</p>
      <p class='static-card-title'>Type of League</p>
      <p class='static-card-content'><q-icon name='trending flat'></q-icon>In the Public League format of the league(s), UCF may offer the league(s) in leagues comprising of 2 Participants, 3 Participants, 4 Participants, 12 Participants, 100 Participants or any other pre-designated number of Participants.</p>
      <p class='static-card-content'><q-icon name='trending flat'></q-icon>UCF may offer this format of the league(s) as a paid format and the Winner will be determinable at the end of the round.</p>
      <p class='static-card-content'><q-icon name='trending flat'></q-icon>The number of Participants required to make the league(s) operational will be pre-specified and once the number of Participants in such league(s) equals the pre-specified number required for that league(s), such league(s) shall be operational. In case the number of Participants is less than the pre-specified number at the time of commencement of the round, such league(s) will not be operational and the participation fee paid by each Participant shall be returned to the account of such User without any charge or deduction.</p>
      <p class='static-card-content'><q-icon name='trending flat'></q-icon> In certain leagues across the Fantasy gaming, designated as "Confirmed Leagues", the league(s) shall become operational once the number of Participants in such league (s) equals the pre-specified number of winners to be declared in such league(s), even if all available Participant slots (as pre-specified in relation to the league(s)) remain unfilled. It is clarified that notwithstanding the activation of such league(s), Participants can continue to join such league(s) till either (i) all available Participant slots of such league(s) are filled or (ii) the round to which the league (s) relates commences, whichever is earlier. In case such league(s) is not operational by the time of the commencement of the round, the participation fee paid by each Participant shall be returned to the account of such User without any charge or deduction.</p>
      <p class='static-card-title'>8.Legality of Game of Skill</p>
      <p class='static-card-content'>Games of skill are legal, as they are excluded from the ambit of Indian gambling legislations including, the Public Gambling Act of 1867.The Indian Supreme Court in the cases of State of Andhra Pradesh v. K Satyanarayana (AIR 1968 SC 825) and KR Lakshmanan v. State of Tamil Nadu (AIR 1996 SC 1153) has held that a game in which success depends predominantly upon the superior knowledge, training, attention, experience and adroitness of the player shall be classified as a game of skill.</p>
      <p class='static-card-content'>The league (s) described above (across the Fantasy gaming) are games of skill as success of Participants depends primarily on their superior knowledge of the games of cricket, cricket statistics, knowledge of players’ relative form, players’ performance in a particular territory, conditions and/or format (such as ODIs, test cricket and Twenty20 in the cricket fantasy game), attention and dedication towards the league(s) and adroitness in playing the league(s). The league(s) also requires Participants to field well-balanced sides with limited resources and make substitutions at appropriate times to gain the maximum points.</p>
      <p class='static-card-content'>By participating in this league(s), each Participant acknowledges and agrees that he/she is participating in a game of skill.</p>
       <p class='static-card-title'>9.Eligibility</p>
      <p class='static-card-content'>The league(s) are open only to persons above the age of 18 years.</p>
      <p class='static-card-content'>The league(s) are open only to persons, currently residing in India.</p>
      <p class='static-card-content'>UCF may, in accordance with the laws prevailing in certain Indian states, bar individuals residing in those states from participating in the league(s). Currently, individuals residing in the Indian states of Assam, Odisha and Telangana may not participate in the paid version of the league as the laws of these states bar persons from participating in games of skill where participants are required to pay to enter.</p>
      <p class='static-card-content'>Persons who wish to participate must have a valid email address.</p>
      <p class='static-card-content'>Only those Participants who have successfully registered on the UCF.com as well as registered prior to each round in accordance with the procedure outlined above shall be eligible to participate in the league and win prizes.</p>
      <p class='static-card-title'>10.Tabulation of fantasy points</p>
      <p class='static-card-content'>TUCF may obtain the score feed and other information required for the computation and tabulation of fantasy points from third party service provider(s). In the rare event that any error in the computation or tabulation of fantasy points, selection of winners, etc., as a result of inaccuracies in or incompleteness of the feed provided by the third party service provider comes to its attention, UCF shall use best efforts to rectify such error prior to the distribution of prizes. However, UCF hereby clarifies that it relies on the accuracy and completeness of such third party score/statistic feeds and does not itself warrant or make any representations concerning the accuracy thereof and, in any event, shall take no responsibility for inaccuracies in computation and tabulation of fantasy points or the selection of winners as a result of any inaccurate or incomplete scores/statistics received from such third party service provider. Users and Participants agree not to make any claim or raise any complaint against UCF in this respect.</p>
       <p class='static-card-title'>11.Selection and Verification of Winners and Conditions relating to the Prizes</p>
      <p class='static-card-content'> <b>Selection of Winners</b>: Winners will be decided on the basis of the scores of the Teams in a designated round (which may last anywhere between one day and an entire tournament) of the league(s). The Participant(s) owning the Team(s) with the highest aggregate score in a particular round shall be declared the Winner(s). In certain pre-specified leagues, UCF may declare more than one Winner and distribute prizes to such Winners in increasing order of their Team's aggregate score at the end of the designated round of the league. The contemplated number of Winners and the prize due to each Winner in such league shall be as specified on the league page prior to the commencement of the league.Participants creating Teams on behalf of any other Participant or person shall be disqualified.In the event of a tie, the winning Participants shall be declared Winners and the prize shall be equally divided among such Participants.UCF shall not be liable to pay any prize if it is discovered that the Winner(s) have not abided by these Terms and Conditions, and other rules and regulations in relation to the use of the UCF.com, league, “Fantasy Rules”, etc.</p>
      <p class='static-card-content'> <b>Contacting Winners</b>: Winners shall be contacted by UCF or the third party conducting the league on the e-mail address provided at the time of registration. The verification process and the documents required for the collection of prize shall be detailed to the Winners at this stage. As a general practice, winners will be required to provide following documents:</p>
      <p class='static-card-content'> <b>Declaration of Winners in case of non fulfillment of required number of participants</b>: If any non-cancellable league is not filled/less number of participants joined than required In such scenarios, league shall not be cancelled and winners shall be declared by UCF. However the amount of winning would be paid proportionally to the users.</p>
      <p class='static-card-content'> <b>The verification process and the documents required for the collection of prize shall be detailed to the Winners at this stage. As a general practice, winners will be required to provide following documents:</b></p>
      <p class='static-card-content'> <q-icon name='trending flat'></q-icon> Orignal scanned copy of the User’s PAN card.</p>
      <p class='static-card-content'> <q-icon name='trending flat'></q-icon>  User’s bank account details and proof of the same.</p>
      <p class='static-card-content'>  UCF shall not permit a Winner to withdraw his/her prize(s)/accumulated winnings unless the above-mentioned documents have been received and verified within the time-period stipulated by UCF. The User represents and warrants that the documents provided in the course of the verification process are true copies of the original documents to which they relate.</p>
      <p class='static-card-content'> The list of Winners shall be posted on a separate web-page on the UCF.com. The winners will also be intimated by e-mail.In the event that a Participant has been declared a Winner on the abovementioned web-page but has not received any communication from UCF, such Participant may contact UCF within the time specified on the webpage.</p>
      <p class='static-card-content'>  <b>Verification process</b>: Only those Winners who successfully complete the verification process and provide the required documents within the time limit specified by UCF shall be permitted to withdraw/receive their accumulated winnings (or any part thereof). UCF shall not entertain any claims or requests for extension of time for submission of documents.</p>
      <p class='static-card-content'> UCF shall scrutinize all documents submitted and may, at its sole and absolute discretion, disqualify any Winner from withdrawing his accumulated winnings (or any part thereof) on the following grounds:</p>
      <p class='static-card-content'> <q-icon name='trending flat'></q-icon>Determination by UCF that any document or information submitted by the Participant is incorrect, misleading, false, fabricated, incomplete or illegible.</p>
      <p class='static-card-content'> <q-icon name='trending flat'></q-icon>Participant does not fulfill the Eligibility Criteria specified in Clause 10 above.</p>
      <p class='static-card-content'> <q-icon name='trending flat'></q-icon>Any other ground.</p>
      <p class='static-card-content'>  <b>Taxes Payable</b>: All prizes shall be subject to deduction of tax (“TDS”) as per the Income Tax Act 1961. Winners will be provided TDS certificates in respect of such tax deductions. The Winners shall be responsible for payment of any other applicable tax, including but not limited to, income tax, gift tax, etc. in respect of the prize money.</p>
      <p class='static-card-content'>  <b>Other important points</b>:The decision of UCF with respect to the awarding of prizes shall be final, binding and non-leagueable. Participants playing the paid formats of the league(s) confirm that they are not residents of any of the following Indian states – Assam, Odisha, and Telangana. If it is found that a Participant playing the paid formats of the league(s) is a resident of any of the abovementioned states, UCF shall disqualify such Participant and forfeit any prize won by such Participant. Further UCF may, at its sole and absolute discretion, suspend or terminate such Participant’s account with UCF.com. Any amount remaining unused in the User’s Game Account or Winnings Account on the date of deactivation or deletion shall be reimbursed to the User by an online transfer to the User’s bank account on record with UCF, subject to the processing fee (if any) applicable on such transfers as set out herein.</p>
      <p class='static-card-content'>  <b>Free Leauge</b>:  UCF is presenting an unbelievable offer in that users can win cash prize without paying any entry charges for the leagues and if you win! the winning amount will get transferred into your unutilized money which can be consumed only for joining other leagues. There is no other way to use or withdraw the winning amount accept joining other leagues. If it is found that a Participant playing the paid formats of the league(s) is under the age of eighteen (18), UCF shall be entitled, at its sole and absolute discretion, to disqualify such Participant and forfeit his/her prize. Further, UCF may, at its sole and absolute discretion, suspend or terminate such Participant’s account.To the extent permitted by law, UCF makes no representations or warranties as to the quality, suitability or merchantability of any prizes and shall not be liable in respect of the same. The Winners shall bear all transaction charges levied for delivery of cash prizes. All prizes are non-transferable and non-refundable. Prizes cannot be exchanged/redeemed for cash or kind. No cash claims can be made in lieu of prizes in kind.</p>
      <p class='static-card-title'>12.Publicity &amp; Promotions</p>
      <p class='static-card-content'>Acceptance of a prize by the Winner constitutes permission for UCF, and its affiliates to use the Winner's name, likeness, voice and comments for advertising and promotional purposes in any media worldwide for purposes of advertising and trade without any further permissions or consents and/or additional compensation whatsoever. The Winners further undertake that they will be available for promotional purposes as planned and desired by UCF without any charge. The exact dates remain the sole discretion of UCF. Promotional activities may include but not be limited to press events, internal meetings, and ceremonies/functions.</p>
      <p class='static-card-title'>13.General Guidelines</p>
      <p class='static-card-content'>If it comes to the notice of UCF that any governmental, statutory or regulatory compliances or approvals are required for conducting any league(s) or if it comes to the notice of UCF that conduct of any such league(s) is prohibited, then UCF shall withdraw and / or cancel such league(s) without prior notice to any Participants or winners of any league(s). Users agree not to make any claim in respect of such cancellation or withdrawal of the league or league it in any manner. Employees, directors, affiliates, relatives and family members of UCF, will not be eligible to participate in any league(s).</p>
      <p class='static-card-title'>14.Dispute and Resolution</p>
      <p class='static-card-content'>The courts of competent jurisdiction at Bangalore shall have exclusive jurisdiction to determine any and all disputes arising out of, or in connection with, the Fantasy gaming provided by UCF (including the league(s)), the construction, validity, interpretation and enforceability of these Terms and Conditions, or the rights and obligations of the User(s) (including Participants) or UCF, as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below. All such issues and questions shall be governed and construed in accordance with the laws of the Republic of India.</p>
      <p class='static-card-content'>In the event of any legal dispute (which may be a legal issue or question) which may arise, the party raising the dispute shall provide a written notification (“Notification”) to the other party. On receipt of Notification, the parties shall first try to resolve the dispute through discussions. In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt of Notification, the dispute shall be settled by arbitration.</p>
      <p class='static-card-content'>The place of arbitration shall be Bangalore, India. All arbitration proceedings shall be conducted in English and in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time.</p>
      <p class='static-card-content'>The arbitration award will be final and binding on the Parties, and each Party will bear its own costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise. The arbitrator shall be entitled to pass interim orders and awards, including the orders for specific performance and such orders would be enforceable in competent courts. The arbitrator shall give a reasoned award.</p>
      <p class='static-card-content'>Nothing contained in these Terms and Conditions shall prevent UCF from seeking and obtaining interim or permanent equitable or injunctive relief, or any other relief available to safeguard UCF’s interest prior to, during or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from any court having jurisdiction to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of UCF to pursue any remedy for monetary damages through the arbitration described herein.</p>
      <p class='static-card-title'>15.Release and Limitations of Liability</p>
      <p class='static-card-content'>Users shall access the Fantasy gaming provided on the UCF.com voluntarily and at their own risk. UCF shall, under no circumstances be held responsible or liable on account of any loss or damage sustained (including but not limited to any accident, injury, death, loss of property) by Users or any other person or entity during the course of access to the Fantasy gaming (including participation in the league(s)) or as a result of acceptance of any prize.</p>
      <p class='static-card-content'>By entering the UCF.com and accessing the Fantasy gaming provided therein, Users hereby release from and agree to indemnify UCF, and/ or any of its directors, employees, partners, associates, and licensors, from and against all liability, cost, loss or expense arising out their access to the Fantasy gaming including (but not limited to) personal injury and damage to property and whether direct, indirect, consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.</p>
      <p class='static-card-content'>UCF accepts no liability, whether jointly or severally, for any errors or omissions, whether on behalf of itself or third parties in relation to the prizes.</p>
      <p class='static-card-content'>Users shall be solely responsible for any consequences which may arise due to their access of Fantasy gaming by conducting an illegal act or due to non-conformity with these Terms and Conditions and other rules and regulations in relation to Fantasy gaming, including the provision of an incorrect address or other personal details. Users also undertake to indemnify UCF and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of an attorney, legal charges etc.) on a full indemnity basis for any loss/damage suffered by UCF on account of such act on the part of the Users.</p>
      <p class='static-card-content'>Users shall indemnify, defend, and hold UCF harmless from any third party/entity/organization claims arising from or related to such User’s engagement with the UCF.com or participation in any league. In no event shall UCF be liable to any User for acts or omissions arising out of or related to User’s engagement with the UCF.com or his/her participation in any league(s).</p>
      <p class='static-card-content'>In consideration of UCF allowing Users to access the Fantasy gaming hosted on the UCF.com, to the maximum extent permitted by law, the Users waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against UCF, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of Fantasy gaming or related to the leagues or the prizes of the leagues.</p>
       <p class='static-card-title'>16.Disclaimers</p>
      <p class='static-card-content'>To the extent permitted under law, neither UCF nor its parent/holding company, subsidiaries, affiliates, directors, officers, professional advisors, employees shall be responsible for the deletion, the failure to store, the misdelivery, or the untimely delivery of any information or material.</p>
      <p class='static-card-content'>To the extent permitted under law, UCF shall not be responsible for any harm resulting from downloading or accessing any information or material, the quality of servers, games, products, Fantasy gaming or sites, cancellation of competition and prizes. UCF disclaims any responsibility for, and if a User pays for access to one of UCF’s Fantasy gaming the User will not be entitled to a refund as a result of, any inaccessibility that is caused by UCF’s maintenance on the servers or the technology that underlies our sites, failures of UCF’s service providers (including telecommunications, hosting, and power providers), computer viruses, natural disasters or other destruction or damage of our facilities, acts of nature, war, civil disturbance, or any other cause beyond our reasonable control. In addition, UCF does not provide any warranty as to the content on the UCF.com(s). UCF.com(s) content is distributed on an “as is, as available” basis.</p>
      <p class='static-card-content'>Any material accessed, downloaded or otherwise obtained through UCF.com is done at the User’s discretion, competence, acceptance and risk, and the User will be solely responsible for any potential damage to User’s computer system or loss of data that results from a User’s download of any such material.</p>
      <p class='static-card-content'><b>UCF shall make best endeavors to ensure that the UCF.com(s) is error-free and secure, however, neither UCF nor any of its partners, licensors or associates makes any warranty that:</b></p>
       <p class='static-card-content'> <q-icon name='trending flat'></q-icon>The UCF.com(s) will meet Users’ requirements.</p>
        <p class='static-card-content'> <q-icon name='trending flat'></q-icon>UCF.com(s) will be uninterrupted, timely, secure, or error-free.</p>
         <p class='static-card-content'> <q-icon name='trending flat'></q-icon>The results that may be obtained from the use of UCF.com(s) will be accurate or reliable.</p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>The quality of any products, Fantasy gaming, information, or other material that Users purchase or obtain through UCFcom(s) will meet Users’ expectations.</p>
          <p class='static-card-content'> In case UCF discovers any error, including any error in the determination of Winners or in the transfer of amounts to a User’s account, UCF reserves the right (exercisable at its discretion) to rectify the error in such manner as it deems fit, including through a set-off of the erroneous payment from amounts due to the User or deduction from the User’s account of the amount of erroneous payment. In case of exercise of remedies in accordance with this clause, UCF agrees to notify the User of the error and of the exercise of the remedy (ies) to rectify the same.</p>
          <p class='static-card-content'> To the extent permitted under law, neither UCF nor its partners, licensors or associates shall be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use our sites, even if we have been advised of the possibility of such damages.</p>
          <p class='static-card-content'> Any Fantasy gaming, events or league(s) being hosted or provided, or intended to be hosted or provided by UCF and requiring specific permission or authority from any statutory authority or any state or the central government, or the board of directors shall be deemed cancelled or terminated, if such permission or authority is either not obtained or denied either before or after the availability of the relevant Fantasy gaming, events or league(s) are hosted or provided.</p>
          <p class='static-card-content'> To the extent permitted by law, in the event of suspension or closure of any Services, events or leagues, Users (including Participants) shall not be entitled to make any demands, claims, on any nature whatsoever.</p>
          <p class='static-card-title'> 17.Refund </p>
          <p class='static-card-content'> A transaction, once confirmed, is final and no cancellation is permissible. However, UCF may, at its sole and absolute discretion, permit a User to cancel a transaction and refund the amount paid:If the User sends a written request to UCF from the registered email Id to cancel such payment; or If the payment is made for participation in the paid version(s) of the league(s), the cancellation request must be received at least 2 days prior to the commencement of the round in respect of which the payment is made; UCF shall not be liable to refund any amount thereafter.</p>
          <p class='static-card-content'> UCF may, at its sole and absolute discretion, refund the amount to the User after deducting applicable cancellation charges and taxes. At the time of the transaction, Users may also be required to take note of certain additional terms and conditions and such additional terms and conditions shall also govern the transaction. To the extent that the additional terms and conditions contain any clause that is conflicting with the present terms and conditions, the additional terms and conditions shall prevail.</p>
          <p class='static-card-title'> Requirements.</p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>  Mobile No </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   E-Mail ID  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>    PAN CARD   </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>    Govt ID (For Residence proof)  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>    Bank details - Name, Bank Name, DOB, Branch, IFSC Code, State  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   All image which you provide should be of original document's scan copy.  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   PAN card details and Account details should match. </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   PAN card should not be older than 1977's person.  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   Kindly provide documents which are asked.  </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>    If we find any type of spamming on site or do any suppicipous activity, account will be blocked. </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   All type of request will be verified within 1-3 working days. We will update you when your request will be verified or there is an update.   </p>
          <p class='static-card-content'> <q-icon name='trending flat'></q-icon>   30.9% Tax will be deducted from your winnings which is more than 10,000 RS. </p>
          <p class='static-card-title'>    18.Referal Bonus </p>
          <p class='static-card-content'>   If any existing user refer any prospective user and such user play any paid league in UCF, Both will get INR 250 each subject to following condition: User can not withdraw bonus amount. However any winnings from such bonus amount is withdrawable. </p>
          <p class='static-card-content'>    Prospective user would get bonus amount of INR 250 immediately after successful verification of Mobile no. and email Id, however the user who referred shall get their bonus only after any deposit made by the prospective user (minimum deposit amount is INR 100) </p>
            <p class='static-card-title'> 19.Miscellaneous </p>
          <p class='static-card-content'>   UCF may be required under certain legislation, to notify User(s) of certain events. User(s) hereby acknowledge and consent that such notices will be effective upon UCF posting them on the UCF.com or delivering them to the User through the email address provided by the User at the time of registration. User(s) may update their email address by logging into their account on the UCF.com. If they do not provide UCF with accurate information, UCF cannot be held liable for failure to notify the User. </p>
          <p class='static-card-content'>    UCF shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including but not limited to any failure to perform due to unforeseen circumstances or cause beyond UCF’s control such as acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, network infrastructure failures, strikes, or shortages of transportation facilities, fuel, energy, labor or materials or any cancellation of any football match to which a league relates. In such circumstances, UCF shall also be entitled to cancel any related league(s) and to process an appropriate refund for all Participants. </p>
          <p class='static-card-content'> UCF’s failure to exercise or enforce any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision.</p>
          <p class='static-card-content'> Users agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the UCF.com or these Terms must be filed within thirty (30) days of such claim or cause of action arising or be forever barred.</p>
          <p class='static-card-content'> These Terms and Conditions, including all terms, conditions, and policies that are incorporated herein by reference, constitute the entire agreement between the User(s) and UCF Gaming Private Limited and govern your use of the UCF.com, superseding any prior agreements that any User may have with UCF Gaming Private Limited.</p>
          <p class='static-card-content'>    If any part of these Terms and Conditions is determined to be indefinite, invalid, or otherwise unenforceable, the rest of these Terms and Conditions shall continue in full force. </p>
          <p class='static-card-content'>  UCF reserves the right to moderate, restrict or ban the use of the UCF.com, specifically to any User, or generally, in accordance with UCF’s policy/policies from time to time, at its sole and absolute discretion and without any notice. </p>
          <p class='static-card-content'> UCF may, at its sole and absolute discretion, permanently close or temporarily suspend any Fantasy gaming (including any league(s)). </p>
          <p class='static-card-content'>    All judicial matter will be subjected in Bangalore judicial area.  </p>


     </q-card-main>
</q-card>
 </div>
</div>
</template>
<script>
export default {
  
}
</script>
